import Head from "next/head";
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {

  const getLayout = Component.getLayout || ((page) => page);


  return   <>
    <Head>
      <title>Default</title>
      <meta name="description" content="Generated by create next app" />
      {/*<link rel="icon" href="./favicon.ico" />*/}
    </Head>
    {getLayout(<Component {...pageProps} />)}
  </>
}

export default MyApp
