import Head from "next/head";
import '../styles/globals.css'
import { DAOContextProvider } from "./api/connect";

function MyApp({ Component, pageProps }) {

  const getLayout = Component.getLayout || ((page) => page);


  return   <>
    <Head>
      <title>Default</title>
      <meta name="description" content="Generated by create next app" />
      {/*<link rel="icon" href="./favicon.ico" />*/}
    </Head>
    <DAOContextProvider>
      {getLayout(<Component {...pageProps} />)}
    </DAOContextProvider>

  </>
}

export default MyApp
